version: '3'

volumes:
  db:

services:
  nginx:
      image: nginx:latest
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - app
      ports:
        - "80:80"

  app:
    image: chat:latest
    restart: unless-stopped
    env_file: 
      - .env
    labels:
      maintainer: "Shai Hod"
    links:
      - db
    depends_on:
      - db

  db:
    container_name: chat_db
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: chat
      MYSQL_USER: flask
      MYSQL_PASSWORD: flask
      MYSQL_ROOT_PASSWORD: root
